language: node_js

node_js:
  - "10"
  - "9"
  - "8"
  - "6"

script: echo "Running tests against $(node -v) ..."

include:
    - stage: coveralls
      node_js: "10"
      script: yarn lint && yarn coverage && yarn coveralls

# Allow Travis tests to run in containers.
sudo: false
