language: node_js

node_js:
  - "9"
  - "8"
  - "7"
  - "6"

install:
  - npm install -g npm@latest
  - npm install -g coveralls
  - npm install

script:
  - npm test
  - npm run coverage
  - coveralls < ./coverage/lcov.info || true # if coveralls doesn't have it covered

# Allow Travis tests to run in containers.
sudo: false
