language: node_js

node_js:
  - "10"
  - "9"
  - "8"
  - "6"

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: Coverage Report
      node_js: "10"
      install: 
        - yarn global add coveralls
        - yarn
      script: yarn lint && yarn coverage && yarn coveralls

# Allow Travis tests to run in containers.
sudo: false
