language: node_js

node_js:
  - "10"
  - "9"
  - "8"
  - "6"

install:
  - npm install -g npm@latest
  - npm install -g coveralls
  - npm install

script:
  - npm test

# Allow Travis tests to run in containers.
sudo: false
