name: Publish Preview

on:
  pull_request:
    branches:
      - master
      - release-*

jobs:
  preview: 
    name: Publish Preview Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: NPM Publish Preview
      uses: minkimcello/actions/publish-pr-preview@mk/resideo-zeus 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_POST_COMMENT_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
##
